{% set name = "py4xs" %}
{% set version = "2021.10.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 206f0b629ddf0cb2de870dff11a6410f22ba6ccbd7e115178365038f62175ccd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - fabio
    - h5py
    - matplotlib-base
    - numpy
    - pillow
    - scipy

test:
  imports:
    - py4xs
    - py4xs.atsas
    - py4xs.data2d
    - py4xs.detector_config
    - py4xs.exp_para
    - py4xs.hdf
    - py4xs.local
    - py4xs.mask
    - py4xs.slnxs
    - py4xs.utils

about:
  home: https://pypi.org/project/py4xs
  license: MIT
  license_file: LICENSE.txt
  summary: py4xs - a python package for processing x-ray scattering data
  dev_url: https://github.com/NSLS-II-LIX/py4xs

extra:
  recipe-maintainers:
    - lyang11973
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
